[tool.poetry]
name = "hello-world"
version = "0.1.0"
description = "A basic Python project that prints 'Hello, world!'"
authors = ["Aalhad aalhad.patankar@gmail.com"]
license = "MIT"
readme = "README.md"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"